### ISSUE TITLE
NPE on clicking start when boot hasn't completed yet

### ISSUE THREAD

**Issue by pelzvieh** [pelzvieh/IPv6Droid#23]
```
  java.lang.IllegalStateException: Could not execute method of the activity
    at android.view.View$1.onClick(View.java:4007)
    at android.view.View.performClick(View.java:4756)
    at android.view.View$PerformClick.run(View.java:19748)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5256)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
  Caused by: java.lang.reflect.InvocationTargetException
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at android.view.View$1.onClick(View.java:4002)
    ... 11 more
  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.android.server.connectivity.Vpn.prepare(java.lang.String, java.lang.String)' on a null object reference
    at android.os.Parcel.readException(Parcel.java:1546)
    at android.os.Parcel.readException(Parcel.java:1493)
    at android.net.IConnectivityManager$Stub$Proxy.prepareVpn(IConnectivityManager.java:1702)
    at android.net.VpnService.prepare(VpnService.java:157)
    at de.flyingsnail.ipv6droid.android.MainActivity.startVPN(MainActivity.java:159)
    at de.flyingsnail.ipv6droid.android.MainActivity.startVPN(MainActivity.java:145)
    ... 14 more
```

Original comment by: pelzi

**Comment by pelzvieh** [comment]
This problem comes from the depths of Android. Moreover, I could not reproduce the issue. Hopefully it has been fixed by an update of Android.
