### ISSUE TITLE
Race condition on query statistics when tunnel is just about to start or already stopped

### ISSUE THREAD

**Issue by pelzvieh** [pelzvieh/IPv6Droid#31]
java.lang.NullPointerException: Attempt to invoke virtual method 'long de.flyingsnail.ipv6droid.android.VpnThread$CopyThread.getByteCount()' on a null object reference
            at de.flyingsnail.ipv6droid.android.VpnThread.getStatistics(VpnThread.java:957)
            at de.flyingsnail.ipv6droid.android.AyiyaVpnService$StatisticsBinder.getStatistics(AyiyaVpnService.java:219)
            at de.flyingsnail.ipv6droid.android.statusdetail.StatisticsFragment$Updater.run(StatisticsFragment.java:213)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:279)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:152)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:266)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

**Comment by pelzvieh** [comment]
Fixed in revision b1b3f7aa42629e9d44304b85e4b59f34611aeaf0
