### ISSUE TITLE
AyiyaVpnService getting destroyed

### ISSUE THREAD

**Issue by kukulin** [pelzvieh/IPv6Droid#39]
I'm getting this error message when connect via mobile network 
AyiyaVpnService getting destroyed
class java.lang.Exception

When I connect via wifi at home (with IPv6 support)  than VPN is running without issue

Phone is Samsung galaxy A7  with android 6.0.1

**Comment by kukulin** [comment]
I can connect to ipv6 and ping my home network hosts via IPv6 but VPN disconnect after 3 to 5 seconds with this error message :
 java.lang.Exception at de.flyingsnail.ipv6droid.android.AyiyaVpnService.onDestroy(AyiyaVpnService.java:209) at android.app.ActivityThread.handleStopService(ActivityThread.java:4158) at android.app.ActivityThread.access$2500(ActivityThread.java:229) at android.appActivityThread

**Comment by kukulin** [comment]
I try it again today and all work as it should. No idea what was wrong but it is ok now.
